
project_id = "xnwenbiwefelqzemijlc"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[[inbucket.smtp]]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[realtime]
enabled = true

[analytics]
enabled = false

[vector]
enabled = false

[functions]
[functions.generate-educational-video]
verify_jwt = false
