
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnwenbiwefelqzemijlc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhud2VuYml3ZWZlbHF6ZW1pamxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MjU2ODgsImV4cCI6MjA2MjAwMTY4OH0.2uiPw9kDHi2PjBw52esspjsFrUQCdP7uFFKR9sL-6TI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to call our serverless functions
export const callFunction = async (functionName: string, payload: any) => {
  const response = await fetch(`${SUPABASE_URL}/functions/v1/${functionName}`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${SUPABASE_PUBLISHABLE_KEY}`
    },
    body: JSON.stringify(payload)
  });

  if (!response.ok) {
    throw new Error(`Error calling function ${functionName}: ${response.statusText}`);
  }

  return response.json();
};
